# Generated by Django 3.1 on 2020-08-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmAcct',
            fields=[
                ('account', models.IntegerField(db_column='Account', primary_key=True, serialize=False)),
                ('cm_name', models.CharField(blank=True, db_column='CM_Name', max_length=1, null=True)),
                ('cm_mobile', models.CharField(blank=True, db_column='CM_mobile', max_length=1, null=True)),
            ],
            options={
                'db_table': 'CM_ACCT',
                'managed': False,
            },
        ),
    ]
