version: "3.3"

services:
   web:
    build: .
    command: python manage.py runserver --settings=restfulapicrud.settings.prod 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
