# Generated by Django 3.1 on 2020-08-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmAcct',
            fields=[
                ('account', models.IntegerField(primary_key=True, serialize=False)),
                ('exp_date', models.IntegerField()),
            ],
            options={
                'db_table': 'CM_ACCT',
                'managed': False,
            },
        ),
    ]
