# Generated by Django 3.1 on 2020-08-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmDvceInvtr',
            fields=[
                ('account', models.IntegerField()),
                ('seq_nbr', models.IntegerField()),
                ('cm_name', models.TextField(db_column='CM_name')),
                ('cm_type', models.TextField(db_column='CM_type')),
                ('design_cde', models.IntegerField()),
                ('exp_date', models.IntegerField()),
                ('emer_ind', models.CharField(max_length=1)),
                ('cm_rrc', models.CharField(max_length=1)),
                ('cm_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'CM_DVCE_INVTR',
                'managed': False,
            },
        ),
    ]
