# Generated by Django 3.1 on 2020-10-07 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CM_DVCE_INVTR_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cmdvceinvtr',
            options={'managed': False},
        ),
    ]
