# Generated by Django 3.1 on 2020-10-07 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CM_DVCE_INVTR_app', '0003_auto_20201007_1159'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cmdvceinvtr',
            unique_together={('account', 'seq_nbr')},
        ),
    ]
